### ISSUE TITLE
[Compatibility] Mikado incompatible with BioPython 1.69 and newer

### ISSUE THREAD

**Issue by jayceejiao** [lucventurini/mikado#108]
Hi Luca,

When I run mikado serialise with the sample_data, I get the following error message: 
"Process _XmlPickler-0:
Traceback (most recent call last):
  File "/home/jiaochen/miniconda3/envs/mikoda/lib/python3.5/multiprocessing/process.py", line 252, in _bootstrap
    self.run()
  File "/home/jiaochen/miniconda3/envs/mikoda/lib/python3.5/site-packages/Mikado/serializers/blast_serializer/xml_serialiser.py", line 161, in run
    for pickled in self._pickler(filename):
  File "/home/jiaochen/miniconda3/envs/mikoda/lib/python3.5/site-packages/Mikado/serializers/blast_serializer/xml_serialiser.py", line 105, in _pickler
    max_target_seqs=self.__max_target_seqs)
  File "/home/jiaochen/miniconda3/envs/mikoda/lib/python3.5/site-packages/Mikado/serializers/blast_serializer/xml_serialiser.py", line 835, in objectify_record
    current_target, **hit_dict_params)
  File "/home/jiaochen/miniconda3/envs/mikoda/lib/python3.5/site-packages/Mikado/serializers/blast_serializer/utils.py", line 146, in prepare_hit
    hsp_dict, ident, posit = prepare_hsp(hsp, counter)
  File "/home/jiaochen/miniconda3/envs/mikoda/lib/python3.5/site-packages/Mikado/serializers/blast_serializer/utils.py", line 67, in prepare_hsp
    *hsp.aln.get_all_seqs()):
AttributeError: 'MultipleSeqAlignment' object has no attribute 'get_all_seqs'
"
Used commands:
makeblastdb -in uniprot_sprot_plants.fasta -dbtype prot -parse_seqids > blast_prepare.log
blastx -max_target_seqs 5 -num_threads 60 -query mikado_prepared.fasta -outfmt 5 -db uniprot_sprot_plants.fasta -evalue 0.000001 2> blast.log | sed '/^$/d'  > mikado.blast.xml
mikado serialise  -f -lv DEBUG  --json-conf configuration.yaml --xml mikado.blast.xml  --orfs mikado.bed --blast_targets uniprot_sprot_plants.fasta >err.log 2>&1 &

Thanks for your help!

Best,

Chen

[serialise.log](https://github.com/lucventurini/mikado/files/1367411/serialise.log)
[mikado.blast.xml.zip](https://github.com/lucventurini/mikado/files/1367413/mikado.blast.xml.zip)
[err.log](https://github.com/lucventurini/mikado/files/1367412/err.log)

**Comment by lucventurini** [comment]
Hi Chen,
               which version of BioPython are you using? I am looking at the code, and it looks like there were important changes in this section of the library, starting from v1.69. I did not catch that due to an old version of the library being installed on both my personal production system and the Travis virtual machines I use for testing.

I will write a patch to make Mikado compatible with versions of BioPython newer than 1.68. In the meantime, if you downgrade BioPython to 1.68, Mikado serialise will function as expected.

Sorry for the bug, I hope I will have it solved soon.

**Comment by jayceejiao** [comment]
Thanks for your reply. Yes, I am using BioPython 1.70. I will downgrade BioPython to 1.68 and run Mikado serialise again. Will let you know if I encounter other problems.

**Comment by lucventurini** [comment]
This should have been fixed by 834bfe1d2c8. Closing until further notice of bad behaviours.
