### ISSUE TITLE
 - prepare.py:430 - ERROR - prepare - MainProcess - argument of type 'NoneType' is not iterable Traceback (most recent call last):

### ISSUE THREAD

**Issue by kayussky911** [lucventurini/mikado#109]
Hi, Im just trying to try to learn to use Mikado. I ran this command;
mikado prepare --json-conf configuration.yaml
 Basically, Ive got two Augustus gff outputs and a reference genome. but I had this output; 

2017-12-11 11:59:26,871 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /anaconda3/bin/mikado prepare --json-conf configuration.yaml
2017-12-11 11:59:38,208 - prepare - prepare.py:430 - ERROR - prepare - MainProcess - argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/Mikado/preparation/prepare.py", line 409, in prepare
    min_length=args.json_conf["prepare"]["minimum_length"])
  File "/anaconda3/lib/python3.6/site-packages/Mikado/preparation/prepare.py", line 271, in load_exon_lines
    strand_specific=strand_specific)
  File "/anaconda3/lib/python3.6/site-packages/Mikado/preparation/annotation_parser.py", line 253, in load_from_gff
    if row.is_transcript is True or row.feature == "match":
  File "/anaconda3/lib/python3.6/site-packages/Mikado/parsers/GFF.py", line 196, in is_transcript
    if self.is_gene is True and self.feature != "mRNA_TE_gene":
  File "/anaconda3/lib/python3.6/site-packages/Mikado/parsers/gfannotation.py", line 234, in is_gene
    if "transcript:" in self.id:
TypeError: argument of type 'NoneType' is not iterable
2017-12-11 11:59:38,253 - prepare - prepare.py:432 - ERROR - prepare - MainProcess - Mikado has encountered an error, exiting
2017-12-11 11:59:38,254 - prepare - prepare.py:442 - INFO - prepare - MainProcess - Finished

what do you suggest?

thanks
Kay

**Comment by lucventurini** [comment]
Dear Kay,
                 at a hunch, I would think that the problem is that the Augustus GFF by default are not valid GFF3 files, but rather follow an old version of the format more similar to GTF than GFF. Mikado is not currently capable of parsing these non-standard files.
A possible solution might be to re-run augustus with the "--gff3=on" tag. Alternatively, there might be some utility to perform this conversion; for example, a quick google search pointed me to this [script](https://github.com/jorvis/biocode/blob/master/gff/convert_augustus_to_gff3.py), which I have not personally tested.

Cheers 

Luca

**Comment by kayussky911** [comment]
thanks Luca for the reply,
I used gffread in cufflinks to the gff tp gff3 files, one of the gtt3 looks like this;
_scaffold10x_1	AUGUSTUS	CDS	3591	3908	0.61	-	0	transcript_id "g1.t1"; gene_id "g1";
scaffold10x_1	AUGUSTUS	CDS	4003	4530	0.40	-	0	transcript_id "g2.t1"; gene_id "g2";
scaffold10x_1	AUGUSTUS	CDS	31156	31470	0.28	+	0	transcript_id "g3.t1"; gene_id "g3";
scaffold10x_1	AUGUSTUS	CDS	72040	72306	0.67	-	0	transcript_id "g4.t1"; gene_id "g4";
scaffold10x_1	AUGUSTUS	CDS	72500	72970	0.99	-	0	transcript_id "g5.t1"; gene_id "g5";
scaffold10x_1	AUGUSTUS	CDS	87532	88119	0.53	-	0	transcript_id "g6.t1"; gene_id "g6";
scaffold10x_1	AUGUSTUS	CDS	116102	116544	0.85	+	0	transcript_id "g7.t1"; gene_id "g7";
scaffold10x_1	AUGUSTUS	CDS	124428	124601	0.74	+	1	transcript_id "g7.t1"; gene_id "g7";
scaffold10x_1	AUGUSTUS	CDS	124649	124793	0.72	+	1	transcript_id "g7.t1"; gene_id "g7";
scaffold10x_1	AUGUSTUS	CDS	127526	127747	0.75	+	0	transcript_id "g7.t1"; gene_id "g7";
scaffold10x_1	AUGUSTUS	CDS	128808	129110	0.63	+	0	transcript_id "g8.t1"; gene_id "g8";
scaffold10x_1	AUGUSTUS	CDS	141108	141219	0.68	+	0	transcript_id "g9.t1"; gene_id "g9";
scaffold10x_1	AUGUSTUS	CDS	158955	159125	0.80	+	2	transcript_id "g9.t1"; gene_id "g9";
scaffold10x_1	AUGUSTUS	CDS	164728	164938	1.00	+	2	transcript_id "g9.t1"; gene_id "g9";_

here's the Mikado prepare command line used;
mikado configure --list list.txt --reference genome.fa  --mode permissive --scoring worm.yaml --copy-scoring worm.yaml  configuration.yaml

Here's the prepare.log output;
2017-12-12 10:47:41,225 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /anaconda3/bin/mikado prepare --json-conf configuration.yaml
2017-12-12 10:47:50,116 - prepare - prepare.py:442 - INFO - prepare - MainProcess - Finished

There's no error, but at the same then the mikado_prepared.fasta and mikado_prepared.gtf are empty.

any ideas?
thanks

**Comment by lucventurini** [comment]
Dear Kay,
                 these are indeed GTF rather than GFF3 files. If you change the file extension from GFF3 to GTF, Mikado should be able to handle your files correctly.

Cheers

**Comment by kayussky911** [comment]
Hi Luca, thanks for the assistance so far.
I changed the file extensions to GTF, and the configuration file looks like
canada.gtf      ca      True
erins.gtf       eri     True

but, running mikado configure --list list.txt --reference genome.fa  --mode permissive --scoring worm.yaml --copy-scoring worm.yaml  configuration.yaml
 and mikado prepare --json-conf configuration.yaml

still gives the error;
2017-12-12 14:43:50,352 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /anaconda3/bin/mikado prepare --json-conf configuration.yaml
2017-12-12 14:43:50,610 - prepare - prepare.py:430 - ERROR - prepare - MainProcess - None
Traceback (most recent call last):
  /anaconda3/lib/python3.6/site-packages/Mikado/preparation/prepare.py", line 409, in prepare
    min_length=args.json_conf["prepare"]["minimum_length"])
  File "/anaconda3/lib/python3.6/site-packages/Mikado/preparation/prepare.py", line 280, in load_exon_lines
    strand_specific=strand_specific)
  File "/anaconda3/lib/python3.6/site-packages/Mikado/preparation/annotation_parser.py", line 434, in load_from_gtf
    exon_lines[row.id]["tid"] = row.transcript
KeyError: None
2017-12-12 14:43:50,612 - prepare - prepare.py:432 - ERROR - prepare - MainProcess - Mikado has encountered an error, exiting
2017-12-12 14:43:50,612 - prepare - prepare.py:442 - INFO - prepare - MainProcess - Finished

am thinking of repeating braker over again, but could it be because there's no junction.bed file, I don't have portcullis or something wrong with the configuration file. (the list.txt)

cheers
Kay

**Comment by lucventurini** [comment]
Dear Kay,
                this error is most likely due to some lines in your GTF which do not have a  "transcript_id" feature.
 
$ grep -v transcript_id canada.gtf | grep -v "^#"

should give you the offending lines.

Cheers
