### ISSUE TITLE
Issue with mikado configure

### ISSUE THREAD

**Issue by SchreiberM** [lucventurini/mikado#116]
Hi,

I've downloaded Mikado v.1.1.1 through Bioconda and had was not able to create a configure.yaml file. 
Downgrading to 1.0.2 worked, so I'm using this version at the moment.

Following problem on version 1.1.1:

Setting the parameters as the following:
mikado configure --list List.txt --reference $ref  --mode permissive --scoring plants.yaml --copy-scoring plants.yaml configuration.yaml

produced a configuration.yaml file, but the header states that it created a Daijin configuration file, not one for Mikado.

Including the parameter --full (as below)
mikado configure --full --list List.txt --reference $ref  --mode permissive --scoring plants.yaml --copy-scoring plants.yaml configuration.yaml

resulted in an error message (only included a part here, but would be happy to provide the whole):

2018-04-18 15:47:12,297 - to_json - configurator.py:611 - ERROR - to_json - MainProcess - while parsing a block collection
  in "/tmp/3361.1.md.q/tmpz2iroypv.yaml", line 421, column 3
expected <block end>, but found '?'
  in "/tmp/3361.1.md.q/tmpz2iroypv.yaml", line 422, column 3
Traceback (most recent call last):
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/Mikado/configuration/configurator.py", line 604, in to_json
    json_dict = yaml.load(json_file)
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/mnt/shared/scratch/synology/ms41439/apps/conda/envs/MikadoEnv/lib/python3.6/site-packages/yaml/parser.py", line 393, in parse_block_sequence_entry
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block collection
  in "/tmp/3361.1.md.q/tmpz2iroypv.yaml", line 421, column 3
expected <block end>, but found '?'
  in "/tmp/3361.1.md.q/tmpz2iroypv.yaml", line 422, column 3

Cheers,
Miriam

**Comment by lucventurini** [comment]
Dear Miriam,
                      thank you for your bug report. 

Regarding the first issue, you are right, the default behaviour of Mikado is wrong. I fixed the bug and it will function correctly (ie producing a Mikado-only configuration) from the next version. However, the Daijin configuration you will obtain is still valid for Mikado, so you could run version 1.1 with that configuration.

Regarding the second issue, thank you for reporting it. I have fixed the code now, and it will be fixed in version 1.2 (which should be coming out in the next month).

Both bugs are now kept in check by tests for additional safety.

Best
