### ISSUE TITLE
errors in prepare.log

### ISSUE THREAD

**Issue by uncleflybfchen** [lucventurini/mikado#117]
Many thanks for providing Mikado software.

I am using Mikado in our _de novo_ assembly project. I got the following error messages in prepare.log when running the mikado prepare steps. 

```
2018-04-27 15:10:10,358 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError
2018-04-27 15:10:10,360 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError
2018-04-27 15:10:10,362 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError
2018-04-27 15:10:10,363 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError
2018-04-27 15:10:10,365 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError
2018-04-27 15:10:10,378 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError

```
```
2018-04-27 15:15:06,820 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError

```
```
2018-04-27 15:15:54,844 - prepare - prepare.py:435 - ERROR - prepare - MainProcess - Coordinates (Sequence.start=437 and Sequence.end=436) imply a different length than Sequence.seq (len=0). Did you modify Sequence.seq?
Traceback (most recent call last):
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/prepare.py", line 433, in prepare
    perform_check(sorter(shelf_stacks), shelf_stacks, args, logger)
  File "/home/bfc/.local/lib/python3.5/site-packages/Mikado/preparation/prepare.py", line 163, in perform_check
    str(args.json_conf["reference"]["genome"][chrom][key[0]-1:key[1]]),
  File "/home/bfc/.local/lib/python3.5/site-packages/pyfaidx/__init__.py", line 784, in __getitem__
    return self._fa.get_seq(self.name, start + 1, stop)[::step]
  File "/home/bfc/.local/lib/python3.5/site-packages/pyfaidx/__init__.py", line 135, in __getitem__
    % (self.start, self.end, len(self.seq)))
ValueError: Coordinates (Sequence.start=437 and Sequence.end=436) imply a different length than Sequence.seq (len=0). Did you modify Sequence.seq?
2018-04-27 15:15:54,856 - prepare - prepare.py:437 - ERROR - prepare - MainProcess - Mikado has encountered an error, exiting
2018-04-27 15:15:55,044 - prepare - prepare.py:447 - INFO - prepare - MainProcess - Finished

```

- Are these errors related to my environments?
- How can I fix these errors?
- Although some errors occured, I still got two files, mikado_prepared.fasta and mikado_prepared.gtf. Can I still use these two files in the following steps?

Thanks a lot

**Comment by lucventurini** [comment]
Dear @uncleflybfchen,
                                     many apologies for the late reply.
You have two different errors here:
- In the first case, Mikado is complaining that the length of the FASTA sequence is different from the expected length of the DNA fragment. This is bizarre, and I cannot fathom the origin of the mistake like this. I will try to make the error message more informative.
- In the second case, Mikado is complaining that some transcripts have at least one exon with an expected length of 0 base pairs. This is, of course, invalid, and throws Mikado again into an error.

I would not trust the mikado_prepared files, as they are most probably corrupt and/or incomplete. I have just released a new version of Mikado, which unfortunately does not take care of the issue. I can, however, modify the code in the development branch so that it will sidestep the issue and report something more informative. I will let you know when it is ready.

**Comment by lucventurini** [comment]
Hi @uncleflybfchen , I am about to release a new version which should not have the issues you encountered. I am not closing the issue yet, I would need you to try to rerun Mikado again to see whether the problem has been fixed. 
Kind regards

**Comment by uncleflybfchen** [comment]
Hi @lucventurini , I am very glad to rerun Mikado using the new version. How could I install the new version, follow the old procedure?

**Comment by lucventurini** [comment]
Yes, Mikado can be installed through conda and GitHub. I still have to load the new version on PyPI though, so that method will not be suitable for the time being. I plan to release onto there today or tomorrow.

Ottieni Outlook per Android<https://aka.ms/ghei36>

________________________________

**Comment by SchreiberM** [comment]
Hi, 
I've encountered the same error message as the original post. The new versions still had the same issue, just a different error message.

The problem was my reference file which still contained windows line endings which I think threw the index off. After using dos2unix everything worked fine.

I hope this might help someone.
Cheers,
Miriam

**Comment by lucventurini** [comment]
Hi Miriam, 
                    that would most definitely throw off the parser - it would be a python issue though, rather than specifically about Mikado. Thank you for contributing the workaround!
