### ISSUE TITLE
mikado prepare assertion error

### ISSUE THREAD

**Issue by kayDaramola** [lucventurini/mikado#120]
HI,
I was trying Mikado on some transcript files, 2 of the input gff files are predicted transcripts of different libraries, while the third is a stringtie output generated from the merged reads (bam files) of both assemblies.

I ran **mikado prepare --json-conf configuration.yaml** ALthough I do have a **mikado_prepared.fasta** and **mikado_prepared.gtf** file. But the **prepare. log** file says,

2018-05-15 16:39:36,849 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /pub38/kayussky/anaconda3/bin/mikado prepare --json-conf configuration.yaml
2018-05-15 16:39:59,593 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/pub38/kayussky/anaconda3/lib/python3.6/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/pub38/kayussky/anaconda3/lib/python3.6/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)
AssertionError
2018-05-15 16:39:59,596 - prepare - checking.py:91 - ERROR - create_transcript - MainProcess -
Traceback (most recent call last):
  File "/pub38/kayussky/anaconda3/lib/python3.6/site-packages/Mikado/preparation/checking.py", line 78, in create_transcript
    transcript_object.check_strand()
  File "/pub38/kayussky/anaconda3/lib/python3.6/site-packages/Mikado/transcripts/transcriptchecker.py", line 159, in check_strand
    assert self.exons[-1][1] - self.start + 1 == len(self.fasta_seq)

.............
AssertionError
2018-05-15 16:40:57,463 - prepare - transcriptchecker.py:187 - WARNING - check_strand - MainProcess - Transcript str_MSTRG.5546.1 has 4 positive and 1 negative splice junctions.     Aborting.
2018-05-15 16:41:34,703 - prepare - transcriptchecker.py:187 - WARNING - check_strand - MainProcess - Transcript str_MSTRG.8793.1 has 4 positive and 1 negative splice junctions.     Aborting.
2018-05-15 16:41:35,112 - prepare - transcriptchecker.py:187 - WARNING - check_strand - MainProcess - Transcript str_MSTRG.8830.3 has 1 positive and 1 negative splice junctions.     Aborting.
2018-05-15 16:42:02,307 - prepare - transcriptchecker.py:187 - WARNING - check_strand - MainProcess - Transcript str_MSTRG.11250.2 has 9 positive and 1 negative splice junctions.     Aborting.
2018-05-15 16:42:20,420 - prepare - prepare.py:447 - INFO - prepare - MainProcess - Finished

Not particularly sure why I have these error files, Do I ignore them and just move on, is there anything I should be concerned about, I fear the fasta and gff output files may be incomplete

Thanks 
Kay

**Comment by kayDaramola** [comment]
hi, I think the problem was the stringtie gff, I removed it and used the other two files and the output was:

2018-05-15 17:09:04,426 - prepare - prepare.py:67 - INFO - setup - MainProcess - Command line: /pub38/kayussky/anaconda3/bin/mikado prepare --json-conf configuration.yaml
2018-05-15 17:10:51,580 - prepare - prepare.py:447 - INFO - prepare - MainProcess - Finished

thanks

**Comment by lucventurini** [comment]
Hi Kay,
             sorry for the late reply. I have been looking at this bug already, and you are at least the second person experiencing it.
If your data is not confidential, would you be able to send me the FAI of your genome and the stringtie GTF? I do not need the full genome, just these two files. It would also be helpful to know which version of stringtie you are making use of.

Best

**Comment by kayDaramola** [comment]
Unfortunately, I am not authorized to share data, I would have to check with my PI. 
I would send you a personal email if I get authorized.
thanks

**Comment by lucventurini** [comment]
Closing as no comment for almost six months.
